version: "3.7"
services:
    auth:
        build:
            context: ./auth
            dockerfile: Dockerfile
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./api:/api
        depends_on:
            - mongodb

    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth

    poll:
        build:
            context: ./poll
            dockerfile: Dockerfile
        ports:
            - 3002:3002
        depends_on: 
            - mongodb

    graphql:
        build:
            context: ./gql
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        depends_on: 
            - auth
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - './client:/usr/src/app'
        ports:
            - 3000:3000
        depends_on: 
            - graphql
            - poll